CREATE TABLE Category (
	Id INTEGER IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255)
);

CREATE TABLE Product(
    Id INTEGER IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255),
    Description NVARCHAR(MAX),
    Price INTEGER,
    Available BIT,
    IdCategory INTEGER FOREIGN KEY REFERENCES Category(Id)
)

CREATE TABLE Customer(
    Id INTEGER IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255),
    Email NVARCHAR(255),
    Address NVARCHAR(255)
);

CREATE TABLE [Order](
    Id INTEGER IDENTITY(1,1) PRIMARY KEY,
    Status NVARCHAR(255),
    Date DATE,
    IdCustomer INTEGER FOREIGN KEY REFERENCES Customer(Id)
);

CREATE TABLE ProductOrder(
    IdProduct INTEGER FOREIGN KEY REFERENCES Product(Id),
    IdOrder INTEGER FOREIGN KEY REFERENCES [Order](Id),
);